### ISSUE TITLE
scraper的报错修复

### ISSUE THREAD

**Issue by qzcool** [qzcool/SAC#31]
`Syntax Error: invalid syntax`???

**Comment by chinabright** [comment]
您好，在使用的时候出现错误如下：
Traceback (most recent call last):
  File "C:/temp/SAC-master/SAC-master/sac.py", line 2, in <module>
    from modules.scraper import *
  File "C:/temp/SAC-master/SAC-master\modules\scraper.py", line 88
    except Exception as e:
         ^
SyntaxError: invalid syntax

请问这种可能是哪里出了问题？谢谢。

**Comment by chinabright** [comment]
找到了问题，之前的那一行int(float(...) 少写了一个右括号。

**Comment by bruce4research** [comment]
> 找到了问题，之前的那一行int(float(...) 少写了一个右括号。

您好, 请问 "所有公司人员列表运行时间"这里报错如下:
Traceback (most recent call last) <timed exec> in <module>  TypeError: get_people_list() got an unexpected keyword argument 'company_ID'

这里如何解决呢, 谢谢.

另外就是显著的人员ID似乎都变了. 已有文档中的ID都失效了哦.
